Fix version parameter
blk-io/epirus.github.io pull request #19
Opened 2020-10-19 13:42 UTC by xaviarias

2020-10-19 21:21 UTC, SweeXordious requested changes

2020-10-19 21:21 UTC, SweeXordious commented on docs/sdk/cli.md
> +  Project name. This will also be the default Open API context path but can be changed through the Open API Gradle plugin.
The Context path is specified during generation. This `WEB3J_OPENAPI_NAME` is only specified to set the jersey project name in case we are running multiple apps in the same container: 
```
     * The name is an arbitrary user defined name
     * which is used to distinguish between Jersey applications in the case that more applications
     * are deployed on the same runtime (container). The name can be used for example for purposes
     * of monitoring by JMX when name identifies to which application deployed MBeans belong to.
     * The name should be unique in the runtime.
```

2020-10-20 11:19 UTC, xaviarias commented on docs/sdk/cli.md
> +  Project name. This will also be the default Open API context path but can be changed through the Open API Gradle plugin.
So what name is used as context path ? In the docs says `$projectName` is the default value:

```
contextPath | String | $projectName | Generated Web3j-OpenAPI context path /{contextPath}/...
```

2020-10-20 11:31 UTC, SweeXordious commented on docs/sdk/cli.md
> +  Project name. This will also be the default Open API context path but can be changed through the Open API Gradle plugin.
It is the project name specified during generation. This one is specified during runtime

2020-10-20 11:32 UTC, xaviarias commented on docs/sdk/cli.md
> +  Project name. This will also be the default Open API context path but can be changed through the Open API Gradle plugin.
Ok I seem it must be hard-coded in the annotation.

2022-11-17 15:10 UTC, closed without merging